#!/usr/bin/env python3
"""Compile Forge's audited CUDA true-peak kernel to portable PTX.

This maintenance tool is not used by Cargo or release builds. Release builds
embed the checked-in PTX and therefore require only the NVIDIA driver at run
time. Set NVRTC_LIBRARY when libnvrtc is outside the platform search path.
"""

from __future__ import annotations

import argparse
import ctypes
import ctypes.util
import hashlib
import os
from pathlib import Path


def nvrtc_call(function: object, *arguments: object) -> None:
    result = function(*arguments)
    if result != 0:
        raise RuntimeError(f"NVRTC call failed with status {result}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--architecture", default="compute_52")
    arguments = parser.parse_args()

    library_name = os.environ.get("NVRTC_LIBRARY") or ctypes.util.find_library("nvrtc")
    if not library_name:
        raise SystemExit("libnvrtc was not found; set NVRTC_LIBRARY")
    nvrtc = ctypes.CDLL(library_name)

    program = ctypes.c_void_p()
    source = arguments.source.read_bytes()
    nvrtc_call(
        nvrtc.nvrtcCreateProgram,
        ctypes.byref(program),
        source,
        arguments.source.name.encode(),
        0,
        None,
        None,
    )
    try:
        options = [
            f"--gpu-architecture={arguments.architecture}".encode(),
            b"--std=c++11",
            b"--fmad=true",
            b"--ftz=false",
            b"--prec-div=true",
            b"--prec-sqrt=true",
        ]
        option_array = (ctypes.c_char_p * len(options))(*options)
        status = nvrtc.nvrtcCompileProgram(program, len(options), option_array)

        log_size = ctypes.c_size_t()
        nvrtc_call(nvrtc.nvrtcGetProgramLogSize, program, ctypes.byref(log_size))
        if log_size.value > 1:
            log = ctypes.create_string_buffer(log_size.value)
            nvrtc_call(nvrtc.nvrtcGetProgramLog, program, log)
            print(log.value.decode(errors="replace"), end="")
        if status != 0:
            raise RuntimeError(f"NVRTC compilation failed with status {status}")

        ptx_size = ctypes.c_size_t()
        nvrtc_call(nvrtc.nvrtcGetPTXSize, program, ctypes.byref(ptx_size))
        ptx = ctypes.create_string_buffer(ptx_size.value)
        nvrtc_call(nvrtc.nvrtcGetPTX, program, ptx)

        major = ctypes.c_int()
        minor = ctypes.c_int()
        nvrtc_call(nvrtc.nvrtcVersion, ctypes.byref(major), ctypes.byref(minor))
        digest = hashlib.sha256(source).hexdigest()
        provenance = (
            f"// Generated by NVRTC {major.value}.{minor.value} for "
            f"{arguments.architecture}\n"
            f"// Source SHA-256: {digest}\n"
        ).encode()
        arguments.output.write_bytes(provenance + ptx.raw.rstrip(b"\0\r\n") + b"\n")
    finally:
        nvrtc.nvrtcDestroyProgram(ctypes.byref(program))


if __name__ == "__main__":
    main()
